/**
 * Photoshop Script: Import Text Layers from JSON Manifest
 * 
 * Usage:
 *   1. Open the PSD file generated by generate_psd() in Photoshop
 *   2. Run this script: File > Scripts > Other Scripts... > import_text_layers.jsx
 *   3. Select the text_manifest.json file from the same job folder
 *   4. The script will create editable text layers at the OCR-detected positions
 * 
 * Expected JSON format (text_manifest.json):
 *   [
 *     { "text": "Hello", "conf": 95, "bbox": [10, 20, 100, 50] },
 *     { "text": "World", "conf": 92, "bbox": [10, 60, 100, 90] }
 *   ]
 * 
 * Bounding box format: [left, top, right, bottom]
 */

// Enable double-click dialogs
#target photoshop
app.bringToFront();

// Step 1: Ask user to select the text_manifest.json file
var file = File.openDialog("Select text_manifest.json", "JSON Files:*.json,All Files:*");
if (!file) {
    alert("No file selected. Exiting.");
    $.quit();
}

// Step 2: Read JSON file
var jsonText = "";
if (file.open("r")) {
    jsonText = file.read();
    file.close();
} else {
    alert("Cannot read file: " + file);
    $.quit();
}

// Step 3: Parse JSON
var textEntries = [];
try {
    textEntries = JSON.parse(jsonText);
} catch (e) {
    alert("Invalid JSON: " + e);
    $.quit();
}

if (!Array.isArray(textEntries) || textEntries.length === 0) {
    alert("No text entries found in JSON");
    $.quit();
}

// Step 4: Check document is open
if (app.documents.length === 0) {
    alert("No PSD document open. Please open the PSD file first.");
    $.quit();
}

var doc = app.activeDocument;

// Step 5: Create text layers for each entry
var createdLayers = 0;
for (var i = 0; i < textEntries.length; i++) {
    var entry = textEntries[i];
    
    // Validate entry
    if (!entry.text || !entry.bbox || entry.bbox.length < 4) {
        continue;  // Skip invalid entries
    }
    
    var textContent = entry.text;
    var bbox = entry.bbox;  // [left, top, right, bottom]
    var left = bbox[0];
    var top = bbox[1];
    var right = bbox[2];
    var bottom = bbox[3];
    
    try {
        // Create text layer
        var textLayer = doc.artLayers.add();
        textLayer.kind = LayerKind.TEXT;
        textLayer.name = textContent.length > 30 ? textContent.substring(0, 30) : textContent;
        
        // Set text layer position
        var textObject = textLayer.textItem;
        textObject.contents = textContent;
        textObject.position = [left, top];
        textObject.width = Math.max(right - left, 10);
        textObject.height = Math.max(bottom - top, 10);
        
        // Optional: Set text properties for consistency
        textObject.size = Math.max(bottom - top - 4, 10);  // Font size based on bbox height
        textObject.font = "Arial";
        textObject.color.rgb.hexValue = "000000";  // Black text
        
        createdLayers++;
    } catch (e) {
        // Skip text entries that fail
    }
}

// Step 6: Completion message
alert("Successfully created " + createdLayers + " text layers from " + textEntries.length + " entries.");
